name: PHPCS

on:
  push:
  workflow_dispatch:

jobs:
  phpcs:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: MilesChou/php-tools-action/phpcs@master
        with:
          args: 'src'