#https://github.com/marketplace/actions/php-tool-action
name: PHPMD

on:
  push:
  workflow_dispatch:

jobs:
  phpmd:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: MilesChou/php-tools-action/phpmd@master
        with:
          args: 'src text codesize,unusedcode,naming'